apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  security:
    config:
    tls:
      http:
        generate: true
      transport:
        generate: true
        perNode: true
  general:
    httpPort: 9200
    serviceName: my-first-cluster
    version: "2.19.1"
    pluginsList: ["repository-s3","https://github.com/Virtimo/prometheus-exporter-plugin-for-opensearch/releases/download/v2.19.1/prometheus-exporter-2.19.1.0.zip"]
    drainDataNodes: true
  dashboards:
    service:
      type: NodePort
    tls:
      enable: true
      generate: true
    version: 2.19.1
    enable: true
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      resources:
        requests:
          memory: "2Gi"
          cpu: "1000m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
      roles:
        - "cluster_manager"
      persistence:
        emptyDir: {}
    - component: data
      replicas: 2
      resources:
        requests:
          memory: "2Gi"
          cpu: "1000m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
      roles:
        - "data"
      persistence:
        pvc:
          storageClass: managed-nfs-storage
          accessModes:
            - ReadWriteOnce
