name: Scale Down OpenSearch Cluster

on:
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  scale:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Increase data node replicas
        run: |
          echo "Increasing data node replicas in cluster.yml"
          yq -i '.spec.nodePools[] |= (select(.component == "data") .replicas -= 1)' cluster.yml

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add cluster.yml
          git commit -am "🔁 Auto-scale OpenSearch data node replicas"
          git push

